### ISSUE TITLE
Images & Code tags

### ISSUE THREAD

**Issue by lukasoppermann** [worddrop/bookworm#1]
Hey,

are you planning on taking images into consideration for the reading time? Also, I have the feeling that code tags are generally read more slowly than normal text, as you have to comprehend it, do you have any plans of providing an option to allow for a custom reading time for code?

**Comment by jeroenvisser101** [comment]
@lukasoppermann I haven't worked on this project for a long time, but that would be really cool. I don't know exactly if it's easy to say how much time images will cost to read, and some images (charts etc.) might take longer to interpret than others. For code, it might be even harder, but a estimation is easier. I think for code, you could parse code yourself quite easily (since code can be in `<pre>`, `<code>` or markdown code blocks) and then edit the WPM of the parser, and get a fair estimate.

**Comment by lukasoppermann** [comment]
Well, medium apparently has a bit complicated way for images (12s for the first and -1s for all subsequent), but seriously, if there is just a number to set, like 12s it should be good for the beginning and could be fine tuned later on.

For code, your suggestion sounds pretty good, of course this is just an estimate, but I feel its fine since the whole reading time is an estimate as it uses an average WPM count in any case. 

So are you going to try to implement something like this?

**Comment by jeroenvisser101** [comment]
I can try to figure something out, but you're welcome to submit a PR as well, if you feel like doing it :)
